name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-node-20:
    uses: ./.github/workflows/ci.yml
    with:
      node-version: '20'

  build-node-22:
    uses: ./.github/workflows/ci.yml
    with:
      node-version: '22'
